version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend
  db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - db-data:/data/db
    networks:
      - backend
  app:
    image: psykzz/status-api
    ports:
      - 3000:3000
    environment:
      - DEBUG=status-api:*
    networks:
      - backend
    depends_on:
      - redis
      - db

networks:
  backend:

volumes:
  db-data:
